EJERCICIOS DE FUNCIONES

1. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. Crea un *array*, puede ser bidimensional, con valores entre 0-100.

In [28]:
import numpy as np

array_bidimensional = np.random.randint(1, 100, size = (3, 4))

print(f"El array bidimensional que tenemos es: \n{array_bidimensional}")

El array bidimensional que tenemos es: 
[[43 17 29 59]
 [20 39 35 78]
 [95 17 69 12]]


##### Calcula:

- La media de los elementos.

In [29]:
media = np.mean(array_bidimensional)

print(f"El cálculo de la media de todos los elementos del array es: \n{media}")

El cálculo de la media de todos los elementos del array es: 
42.75


- La media de las columnas y redondéalo a dos decimales.

In [30]:
media_columnas = np.mean(array_bidimensional, axis = 0)

media_columnas_redondeada = np.round(media_columnas, decimals=2)

print(f"La media redondeada de cada columnas del array es: \n{media_columnas_redondeada}")

La media redondeada de cada columnas del array es: 
[52.67 24.33 44.33 49.67]


- El valor máximo de cada fila.

In [31]:
maximo_fila = np.max(array_bidimensional, axis = 1)

print(f"El valor maxixmo de cada fila del array es: \n{maximo_fila}")

El valor maxixmo de cada fila del array es: 
[59 78 95]


  - El valor mínimo de cada fila.

In [32]:
minimo_fila = np.min(array_bidimensional, axis = 1)

print(f"El valor minimo de cada fila del array es: \n{minimo_fila}")

El valor minimo de cada fila del array es: 
[17 20 12]


- Hay algun valor que sea mayor que 90 en tu *array*.

In [33]:
array_bidimensional = np.any(array_bidimensional > 90)

if array_bidimensional:
    print("Sí, hay valores mayores que 90 en el array.")
else:
    print("No, no hay valores mayores que 90 en el array.")

Sí, hay valores mayores que 90 en el array.


- Donde los podemos encontrar, cuáles son sus índices.

In [34]:
indices = np.where(array_bidimensional > 90)

print("Los valores mayores que 90 se encuentran en los siguientes índices:", indices)

Los valores mayores que 90 se encuentran en los siguientes índices: (array([], dtype=int64),)


- Ordena el *array* de mayor a menor.

In [36]:
array_bidimensional = np.random.randint(1, 100, size = (3, 4))

array_ordenado_filas = np.sort(array_bidimensional, axis = 1)

array_ordenado_filas = array_ordenado_filas[:, ::-1]

print("El array ordenado por CADA FILA de mayor a menor es: \n", array_ordenado_filas)

El array ordenado por CADA FILA de mayor a menor es: 
 [[85 85 79 30]
 [68 49 48 32]
 [69 60 41 28]]


In [37]:
array_bidimensional = np.random.randint(1, 100, size = (3, 4))

array_ordenado_columnas = np.sort(array_bidimensional, axis = 0)

array_ordenado_columnas = array_ordenado_columnas[::-1, :]

print("El array ordenado por CADA COLUMNA de mayor a menor es: \n", array_ordenado_columnas)

El array ordenado por CADA COLUMNA de mayor a menor es: 
 [[83 52 44 85]
 [78 17 34 40]
 [77 13 32  5]]


📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentíos libres de practicar otros para ir asentando los conocimientos. 