EJERCICIOS DE INDEXACIÓN

1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae:

In [34]:
import numpy as np

array_unidimensional = np.random.random(50)

print(f"El array unidimensional que tenemos es: \n{array_unidimensional}")

El array unidimensional que tenemos es: 
[0.35445272 0.61452214 0.4563662  0.60794883 0.52892002 0.01835817
 0.80112615 0.05910644 0.92162246 0.4842857  0.54674923 0.7562068
 0.94814109 0.95304919 0.47470592 0.29048055 0.64414137 0.88396775
 0.84555933 0.20598173 0.70042114 0.84655937 0.62623105 0.80641319
 0.90132818 0.86215255 0.44084193 0.5382111  0.34567683 0.94330549
 0.91805056 0.73022422 0.50961613 0.64702061 0.43363217 0.82142765
 0.88017356 0.95969502 0.44318558 0.99509397 0.36178289 0.64190789
 0.85150927 0.61970088 0.20025588 0.35576821 0.21921281 0.37780647
 0.08316431 0.93636764]


 - El primer elemento.

In [35]:
array_unidimensional[0]

0.35445272152547236

- Los elementos que están en posición impar.

In [36]:
array_unidimensional[1::2]

print(f"Los elementos que están en posición impar en el array son: \n{array_unidimensional[1::2]}")

Los elementos que están en posición impar en el array son: 
[0.61452214 0.60794883 0.01835817 0.05910644 0.4842857  0.7562068
 0.95304919 0.29048055 0.88396775 0.20598173 0.84655937 0.80641319
 0.86215255 0.5382111  0.94330549 0.73022422 0.64702061 0.82142765
 0.95969502 0.99509397 0.64190789 0.61970088 0.35576821 0.37780647
 0.93636764]


- Los cuatro primeros elementos.

In [37]:
array_unidimensional[:4]

print(f"Los cuatro primeros elementos del array son: \n{array_unidimensional[:4]}")

Los cuatro primeros elementos del array son: 
[0.35445272 0.61452214 0.4563662  0.60794883]


- Los últimos tres elementos.

In [38]:
array_unidimensional[-3:]

print(f"Los tres últimos elementos del array son: \n{array_unidimensional[-3:]}")

Los tres últimos elementos del array son: 
[0.37780647 0.08316431 0.93636764]


- Los elementos entre el 4 y el 8 (incluido). 

In [39]:
array_unidimensional[4:9]

print(f"Los elementos entre el 4 y el 8 (incluido) del array son: \n{array_unidimensional[4:9]}")

Los elementos entre el 4 y el 8 (incluido) del array son: 
[0.52892002 0.01835817 0.80112615 0.05910644 0.92162246]


2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

In [53]:
array_bidimensional = np.random.random((4, 5))

array_bidimensional

array([[0.87635216, 0.73721872, 0.98291056, 0.52959183, 0.03210455],
       [0.04630443, 0.55459345, 0.48236194, 0.06607767, 0.5373123 ],
       [0.42428142, 0.02796122, 0.35801492, 0.48471008, 0.15060218],
       [0.0282212 , 0.13968513, 0.52139043, 0.68109644, 0.8750587 ]])

- La primera fila y todas las columnas.

In [71]:
array_bidimensional[0,:]

print(f"La primera fila del array y todas las columnas son: \n{array_bidimensional[0,:]}")

La primera fila del array y todas las columnas son: 
[0.87635216 0.73721872 0.98291056 0.52959183 0.03210455]


- Todas las filas pares.

In [72]:
array_bidimensional[0:2]

print(f"Las filas pares del array son: \n{array_bidimensional[0::2]}")

Las filas pares del array son: 
[[0.87635216 0.73721872 0.98291056 0.52959183 0.03210455]
 [0.42428142 0.02796122 0.35801492 0.48471008 0.15060218]]


- La primera columna y todas las filas.

In [73]:
array_bidimensional[:,0]

print(f"La primera columna y todas las filas del array son: \n{array_bidimensional[:,0]}")

La primera columna y todas las filas del array son: 
[0.87635216 0.04630443 0.42428142 0.0282212 ]
