EJERCICIOS DE NUMPY

In [18]:
!pip install numpy

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [2]:
import numpy as np

In [27]:
array = np.random.randint(34, 98, size = (4, 3))

dimensiones = array.shape

tipo_dato = array.dtype

print("Array:")
print(array)
print("\nDimensiones del array:", dimensiones)
print("Tipo de datos de los elementos del array:", tipo_dato)

Array:
[[53 88 44]
 [53 45 80]
 [86 42 35]
 [60 54 93]]

Dimensiones del array: (4, 3)
Tipo de datos de los elementos del array: int64


2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

In [5]:
lista1 = [34,56,71,98, 10]

array_unidimensional = np.array(lista1)

print(f"El array unidimensional creado a partir de la lista es: {array_unidimensional}")

El array unidimensional creado a partir de la lista es: [34 56 71 98 10]


In [8]:
lista2 = [[23,45,89, 56], [12,43,82,44]]

array_bidimensional = np.array(lista2)

print(f"El array bidimensional creado a partir de la lista es: \n {array_bidimensional}")

El array bidimensional creado a partir de la lista es: 
 [[23 45 89 56]
 [12 43 82 44]]


**Bonus**

Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.

In [16]:
print("-------------ARRAY UNIDIMENSIONAL--------------")
print(f"El array unidimensional es: \n {array_unidimensional}")
print(f"La forma del array unidimensional es: {array_unidimensional.shape}")
print(f"El número de dimensiones del array unidimensional es: {array_unidimensional.ndim}")
print(f"El número de elementos del array unidimensional es: {array_unidimensional.size}")
print(f"El tipo de dato que tenemos en el array unidimensional es: {array_unidimensional.dtype}")

-------------ARRAY UNIDIMENSIONAL--------------
El array unidimensional es: 
 [34 56 71 98 10]
La forma del array unidimensional es: (5,)
El número de dimensiones del array unidimensional es: 1
El número de elementos del array unidimensional es: 5
El tipo de dato que tenemos en el array unidimensional es: int64


In [15]:
print("-------------ARRAY BIDIMENSIONAL--------------")
print(f"El array bidimensional es: \n {array_bidimensional}")
print(f"La forma del array biidimensional es: {array_bidimensional.shape}")
print(f"El número de dimensiones del array bidimensional es: {array_bidimensional.ndim}")
print(f"El número de elementos del array bidimensional es: {array_bidimensional.size}")
print(f"El tipo de dato que tenemos en el array bidimensional es: {array_bidimensional.dtype}")

-------------ARRAY BIDIMENSIONAL--------------
El array bidimensional es: 
 [[23 45 89 56]
 [12 43 82 44]]
La forma del array biidimensional es: (2, 4)
El número de dimensiones del array bidimensional es: 2
El número de elementos del array bidimensional es: 8
El tipo de dato que tenemos en el array bidimensional es: int64
