EJERCICIOS DE FILTRADO

1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras.

In [54]:
import numpy as np
array1 = np.random.randint(0, 50, size = 20)

array_bidimensional = array1.reshape(4, 5)

print(f"El array bidimensional que tenemos es: \n{array_bidimensional}")

El array bidimensional que tenemos es: 
[[49 37 14 38 11]
 [16 40 26 15 34]
 [39 12 33  4  3]
 [22 11 30  6 41]]


- Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

In [55]:
resultado_where = np.where((array_bidimensional > 30) | (array_bidimensional < 10), "objetivo", "no es mi objetivo")

print("El resultado del np.where() es: \n", resultado_where)

El resultado del np.where() es: 
 [['objetivo' 'objetivo' 'no es mi objetivo' 'objetivo'
  'no es mi objetivo']
 ['no es mi objetivo' 'objetivo' 'no es mi objetivo' 'no es mi objetivo'
  'objetivo']
 ['objetivo' 'no es mi objetivo' 'objetivo' 'objetivo' 'objetivo']
 ['no es mi objetivo' 'no es mi objetivo' 'no es mi objetivo' 'objetivo'
  'objetivo']]


- Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [56]:
escalar = 10

multiplicacion = array_bidimensional * escalar

print("El resultado de la multiplicacion es:\n", multiplicacion)

El resultado de la multiplicacion es:
 [[490 370 140 380 110]
 [160 400 260 150 340]
 [390 120 330  40  30]
 [220 110 300  60 410]]


2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras.

In [57]:
array2 = np.random.randint(1, 5, size = 20)

array_bidimensional = array2.reshape(4, 5)

print(f"El array bidimensional que tenemos es: \n{array_bidimensional}")

El array bidimensional que tenemos es: 
[[2 3 3 3 2]
 [1 2 4 1 4]
 [4 3 4 1 2]
 [3 1 3 4 2]]


- Suma el primer array con el segundo.

In [58]:
suma = np.add(array1, array2)

print(array1)
print(array2)

print("-------------------------------------------------------------")
print("El resultado de la suma de los dos arrays es:\n", suma)

[49 37 14 38 11 16 40 26 15 34 39 12 33  4  3 22 11 30  6 41]
[2 3 3 3 2 1 2 4 1 4 4 3 4 1 2 3 1 3 4 2]
-------------------------------------------------------------
El resultado de la suma de los dos arrays es:
 [51 40 17 41 13 17 42 30 16 38 43 15 37  5  5 25 12 33 10 43]


- Aplicar la potencia para el primer array elevado al segundo.

In [59]:
potencia = np.power(array1, array2)

print(array1)
print(array2)

print("-------------------------------------------------------------")
print("El resultado de la potencia es:\n", potencia)

[49 37 14 38 11 16 40 26 15 34 39 12 33  4  3 22 11 30  6 41]
[2 3 3 3 2 1 2 4 1 4 4 3 4 1 2 3 1 3 4 2]
-------------------------------------------------------------
El resultado de la potencia es:
 [   2401   50653    2744   54872     121      16    1600  456976      15
 1336336 2313441    1728 1185921       4       9   10648      11   27000
    1296    1681]
